# Add a network for reverse proxy
networks:
  custom_network:
    external: true

services:
  holehe:
    build: .
    container_name: holehe-web
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - custom_network